[package]
name = "bitcoin-send-tx-p2p"
version = "0.1.0"
edition = "2021"

[features]
default = []
tor = ["dep:tokio-socks"]

[dependencies]
anyhow = "1.0"
tokio = { version = "1.20.1", features = ["net", "io-util", "rt-multi-thread", "time"] }
bitcoin = { version = "0.29.0", features = ["rand"] }
async-trait = "0.1.57"
log = "0.4.17"
tokio-socks = { version = "0.5.1", optional = true }

[dev-dependencies]
tokio = { version = "1.20.1", features = ["macros"] }
tokio-test = "0.4.2"
hex = "0.4.3"
env_logger = "0.9.0"